arb-dir: lib/Internationalization-app/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/Internationalization-app/l10n/localizations
synthetic-package: false
